var Constants = {

  USER_PASSWORD_INVALID: 'EL USUARIO O CONTRASEÑA INGRESADOS SON INVALIDOS',
  PASSWORD_CHANGE: 'LA CONTRASEÑA HA CAMBIADO',
  CHANGIN_PASSWORD_ERROR: 'ERROR AL CAMBIAR LA CONTRASEÑA',
  SESION_CLOSE_SUCESS: 'SESION CERRADA CORRECTAMENTE',
  USER_NO_VALID: 'USUARIO NO PERMITIDO EN PLATAFORMA',
  TYPE_FLASH_MESSAGE_ERROR: 'ERROR',
  TYPE_FLASH_MESSAGE_SUCESS: 'SUCESS',
  TYPE_FLASH_MESSAGE_WARNING: 'WARNING',
  TYPE_FLASH_MESSAGE_INFO: 'INFO',
  AUTHENTICATION_REQUIRED: 'DEBE ESTAR LOGEADO PARA IGRESAR A ESTA PARTE DE LA PLATAFORMA',
  RENDERIZING_ERROR: 'ERROR AL RENDERIZAR EL COMPONENTE',
  LOAD_USERS_SUCESS: 'LOS BENEFICIARIOS PRESELECCIONADOS FUERON CARGADOR SATISFACTORIAMENTE A SISAP',
  LOAD_USERS_ERROR: 'HUBO UN ERROR EN LA CARGA DE PRESELECCIONADOS. INTENTELO MAS TARDE O PONGASE EN CONTACTO CON EL ADMINISTRADOR DEL SISTEMA',
  ROLE_BENEFICIARY: 'beneficiary',
  VALIDATION_FIELDS_ERROR: 'LA INFORMACIÓN SUMINISTRADA CONTIENE ERRORES, REVISA E INTENTA DE NUEVO POR FAVOR',
  DOCUMENT_SAVED: 'DOCUMENTO GUARDADO'


};

module.exports = Constants;